#!/usr/bin/env bash

#
# TODO Temporarily disabled because of an issue with our build script
# that fails to push the image on passed test suite
#

MYSQL_PASSWORD="test"
MYSQL_PORT="3306"

SERVICE_NAME=`basename $(pwd) | sed 's/^platform-//'`
IMAGE_NAME="$1"

set -e

function cleanup {
  echo "${IMAGE_NAME}: -$(docker rm $(docker kill ${CONTAINER_ID}))"
  rm "${SERVICE_NAME}.cid"
}

echo "Starting service platform-${SERVICE_NAME}..."
docker run \
  --cidfile="${SERVICE_NAME}.cid" \
  --name "platform-${SERVICE_NAME}" \
  --env MYSQL_ALLOW_EMPTY_PASSWORD="1" \
  --env MYSQL_DATABASE="test" \
  --detach \
  "${IMAGE_NAME}"

CONTAINER_ID=`cat "${SERVICE_NAME}.cid"`

trap cleanup EXIT
echo "${IMAGE_NAME}: +${CONTAINER_ID}"

# wait for MySQL to set up
sleep 10

echo "Running tests..."
docker exec "${CONTAINER_ID}" \
  "mysql" -h"localhost" -P"${MYSQL_PORT}" -uroot test
CODE=$?

exit $CODE
